name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Docker build
        run: docker build -t playwright-tests .
      - name: Run Playwright tests
        run: docker run --rm playwright-tests
      - name: Install Netlify
        if: success()
        run: npm install netlify-cli
      - name: Deploy to Netlify
        if: success()
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
